#[derive(Debug, Clone)]
pub enum Action {
    Tick,
    Key(crossterm::event::KeyEvent),
    Quit,
    GoBack,
    SelectLanguage(usize),
    ToggleLogs,
    ToggleHelp,
    Search(String),
    SearchSuccess(serde_json::Value),
    SearchFailure(String),
    MoveUp,
    MoveDown,
    MoveLeft,
    MoveRight,
    Submit,
    FetchPreview(String),
    PreviewSuccess(String, serde_json::Value),
    PreviewFailure(String),
    CopyLink,
    PlayStream,
    DownloadStream,
    UpdateDownload(Option<f64>, Option<String>),
    CancelDownload,
    FetchDetails(String),
    DetailsSuccess(String, serde_json::Value),
    DetailsFailure(String),
    FetchResources {
        subject_id: String,
        season: usize,
        episode: usize,
        resolution: String,
    },
    ResourcesSuccess(serde_json::Value),
    ResourcesFailure(String),
    PosterSuccess(String, std::sync::Arc<image::DynamicImage>),
    Log(String),
}
