#[derive(Debug, Clone)]
pub enum Action {
    Tick,
    Key(crossterm::event::KeyEvent),
    Quit,
    GoBack,
    SelectLanguage(usize),
    ToggleLogs,
    ToggleHelp,
    Search {
        query: String,
    },
    SelectSuggestion {
        query: String,
    },
    SearchSuccess {
        query: String,
        payload: serde_json::Value,
    },
    SearchFailure(String),
    Suggest(String),
    SuggestSuccess(String, serde_json::Value),
    MoveUp,
    MoveDown,
    MoveLeft,
    MoveRight,
    ClosePopup,
    Submit,
    TabPane,
    FetchPreview(String),
    PreviewSuccess(String, serde_json::Value),
    PreviewFailure(String),
    CopyLink,
    PlayStream,
    ShowSubtitlePopup(String, serde_json::Value),
    LaunchMpv(String, Option<String>),
    DownloadStream,
    UpdateDownload(Option<f64>, Option<String>),
    CancelDownload,
    FetchDetails(String),
    DetailsSuccess(String, serde_json::Value),
    DetailsFailure(String),
    FetchResources {
        subject_id: String,
        season: usize,
        episode: usize,
        absolute_episode_index: usize,
        resolution: String,
    },
    ResourcesSuccess(serde_json::Value),
    ResourcesFailure(String),
    PosterSuccess(String, std::sync::Arc<image::DynamicImage>),
    SearchPosterLoaded(String, Option<std::sync::Arc<image::DynamicImage>>),
    Log(String),
    UpdateAvailable(String),
}
