#[derive(Debug, Clone)]
pub enum Action {
    FocusChange,
    ShowPlayerPicker(String, Option<String>),
    LaunchPlayer(crate::tui::state::PlayerKind, String, Option<String>),
    Tick,
    Key(crossterm::event::KeyEvent),
    Quit,
    GoBack,
    SelectLanguage(usize),
    Resize(u16, u16),
    ToggleHelp,
    Search {
        query: String,
    },
    SelectSuggestion {
        query: String,
    },
    SearchSuccess {
        query: String,
        payload: serde_json::Value,
    },
    SearchFailure(String),
    FetchHomepage {
        tab_id: String,
        page: usize,
    },
    HomepageSuccess {
        tab_id: String,
        page: usize,
        payload: serde_json::Value,
    },
    HomepageFailure(String),
    Suggest(String),
    SuggestSuccess(String, serde_json::Value),
    MoveUp,
    MoveDown,
    MoveLeft,
    MoveRight,
    Submit,
    TabPane,
    FetchPreview(String),
    PreviewSuccess(String, serde_json::Value),
    PreviewFailure(String),
    CopyLink,
    PlayStream(bool),
    ShowSubtitlePopup(String, serde_json::Value, bool),
    LaunchMpv(String, Option<String>),
    DownloadStream,
    UpdateDownload(Option<f64>, Option<String>),
    CancelDownload,
    FetchDetails(String),
    DetailsSuccess(String, serde_json::Value),
    DetailsFailure(String),
    FetchResources {
        subject_id: String,
        season: usize,
        episode: usize,
    },
    ResourcesSuccess(u64, usize, usize, serde_json::Value),
    ResourcesFailure(u64, String),
    PosterSuccess(String, std::sync::Arc<image::DynamicImage>),
    SearchPosterLoaded(String, Option<std::sync::Arc<image::DynamicImage>>),
    UpdateAvailable(String),
}
